name: sticker_widget
description: Sticker Widget is a flutter plugin to flip, rotate, resize, move, delete any widgets.
version: 0.1.1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.5
  freezed: ^2.3.5

flutter:


